import traceback

try:
  res = safenet.getx(params)
  print(res[2])
except Exception as e:
        print('Curl Error [' + e.__doc__ + ']\n' + traceback.format_exc())
        print(res[0])
        print(res[1])
